In [1]:
import numpy as np
import cv2

In [53]:
img = cv2.imread('./images/happy-people.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [54]:
face_cascade = cv2.CascadeClassifier('./haarcascade/haarcascade_frontalface_default.xml')

In [55]:
faces = face_cascade.detectMultiScale2(img)

In [56]:
def face_detection(image,all_faces):
    for x,y,w,h in all_faces[0]:

        cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)

        # center 
        cx,cy = (x+x+w)//2 , (y+y+h)//2
        cv2.circle(image,(cx,cy),w//2,(255,0,255),2)
        
    return image


In [57]:
imgface_detect = face_detection(img,faces)
cv2.imshow('face_detect',imgface_detect)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Face and Eye Detection

In [58]:
eye_cascade = cv2.CascadeClassifier('./haarcascade/haarcascade_eye.xml')

In [60]:
def face_eye_detection(image):
    # step-1: detect face
    faces = face_cascade.detectMultiScale2(image)
    for fx,fy,fw,fh  in faces[0]:
        face_roi = image[fy:fy+fh,fx:fx+fw].copy()# croped face
        cv2.rectangle(image,(fx,fy),(fx+fw,fy+fh),(0,255,0),1)# draw rectangle
        
        # eye detection
        eyes = eye_cascade.detectMultiScale2(face_roi)
        for ex,ey,ew,eh in eyes[0]:
            # circle
            cx = fx+(2*ex+ew)//2
            cy = fy+(2*ey+eh)//2
            r =ew//2
            cv2.circle(image,(cx,cy),r,(0,255,255),2)
            
            
    return image
    
img = face_eye_detection(img)

cv2.imshow('face eye',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# smile

In [61]:
smile_detector = cv2.CascadeClassifier('./haarcascade/haarcascade_smile.xml')

In [165]:
img = cv2.imread('./images/friends.jpg')
image = img.copy()
# step-1: detect face
faces,ndetection = face_cascade.detectMultiScale2(image,minNeighbors=8)
print(ndetection)
#print(faces)
for fx,fy,fw,fh  in faces:
    face_roi = image[fy:fy+fh,fx:fx+fw].copy()# croped face
    cv2.rectangle(image,(fx,fy),(fx+fw,fy+fh),(0,255,0),1)# draw rectangle

    # eye detection
    eyes_pos, ndetection = eye_cascade.detectMultiScale2(face_roi)
    if len(ndetection) >= 1:

        order_of_detection = ndetection.ravel().argsort()
        select_2eyes_dominant_index = order_of_detection[order_of_detection >= (len(order_of_detection) - 2)]
        select_eyes_pos = eyes_pos[select_2eyes_dominant_index]
        print(select_eyes_pos)
        for ex,ey,ew,eh in select_eyes_pos:
            print(ex,ey,ew,eh)
            # circle
            cx = fx+(2*ex+ew)//2
            cy = fy+(2*ey+eh)//2
            r =ew//2
            cv2.circle(image,(cx,cy),r,(255,0,255),2)
            
    # smile
    smile_pos, ndetection = smile_detector.detectMultiScale2(face_roi)
    if len(ndetection) >= 1:

        order_of_detection = ndetection.ravel().argsort()
        smile_index = order_of_detection.max()
        smile_index_pos = smile_pos[smile_index]
        sx,sy,sw,sh = smile_index_pos
        cv2.rectangle(image,(fx+sx,fy+sy),(fx+sx+sw,fy+sy+sh),(0,255,255),2,)
    


    # 

cv2.imshow('face eye',image)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[104]
 [ 84]
 [ 71]]
[[53 27 23 23]
 [16 25 26 26]]
53 27 23 23
16 25 26 26
[[55 22 26 26]
 [16 20 27 27]]
55 22 26 26
16 20 27 27
[[15 32 23 23]
 [45 20 29 29]]
15 32 23 23
45 20 29 29


In [149]:
smile_index_pos

array([23, 62, 50, 25], dtype=int32)